---
workspace: /root

# Default to the latest LTS release.
sonar_download_url: https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-5.1.2.zip
sonar_version_directory: sonarqube-5.1.2

# MySQL database connection details.
sonar_mysql_username: sonar
sonar_mysql_password: sonar

sonar_mysql_host: localhost
sonar_mysql_port: "3306"
sonar_mysql_database: sonar

sonar_mysql_allowed_hosts:
  - "127.0.0.1"
  - "::1"
  - "localhost"
